# config.yaml

settings:
  # The time interval is handled by GitHub Actions cron schedule.
  schedule_interval: "12 hours"

scraper:
  target_url: "https://4kwallpapers.com/random-wallpapers/"
  # UPDATED: Simplified path
  repository_folder: "4uffin/images/scraped"
